name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install Production Dependencies
        run: npm ci --omit=dev

      - name: Create Deployment ZIP
        run: |
          zip -r deploy.zip . \
            -x "*.git*" \
            -x ".github/*" \
            -x "*.env*" \
            -x "*.md" \
            -x "node_modules/*"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload ZIP to S3
        run: |
          aws s3 cp deploy.zip s3://${{ secrets.EB_S3_BUCKET }}/deploys/deploy-${{ github.sha }}.zip

      - name: Create New EB Application Version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "${{ secrets.EB_APP_NAME }}" \
            --version-label "ver-${{ github.sha }}-${{ github.run_attempt }}" \
            --source-bundle S3Bucket="${{ secrets.EB_S3_BUCKET }}",S3Key="deploys/deploy-${{ github.sha }}.zip" \
            --region ${{ secrets.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --application-name "${{ secrets.EB_APP_NAME }}" \
            --environment-name "${{ secrets.EB_ENV_NAME }}" \
            --version-label "ver-${{ github.sha }}-${{ github.run_attempt }}" \
            --region ${{ secrets.AWS_REGION }}

      - name: Wait for Deployment
        run: |
          aws elasticbeanstalk wait environment-updated \
            --application-name "${{ secrets.EB_APP_NAME }}" \
            --environment-name "${{ secrets.EB_ENV_NAME }}" \
            --region ${{ secrets.AWS_REGION }}